/*********************************************************************
 *                
 * Copyright (C) 2003-2004, 2006-2007, 2010,  National ICT Australia (NICTA)
 *                
 * File path:     glue/v4-powerpc64/tcb.h
 * Description:   TCB related functions for Version 4, PowerPC 64
 *                
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *                
 * $Id: tcb.h,v 1.27 2006/10/20 21:32:27 reichelt Exp $
 *                
 ********************************************************************/
#ifndef __GLUE__V4_POWERPC64__TCB_H__
#define __GLUE__V4_POWERPC64__TCB_H__

#ifndef __API__V4__TCB_H__
#error not for stand-alone inclusion
#endif

#include <debug.h>

#include INC_API(syscalls.h)		/* for sys_ipc */
#include INC_API(space.h)
#include INC_ARCH(msr.h)
#include INC_ARCH(frame.h)

/* Upstream defined nearly all of tcb_t's powerpc64 members inline here.  They
   are now the out-of-line tcb_* entry points api/v4/tcb.h declares (after it
   includes this header), and they live in glue/v4-powerpc64/thread.c -- the
   same split the 32-bit port uses.  What stays here is what has to: the two
   context helpers those definitions and the exception glue share, and the
   three global accessors whose callers need them inlined. */

/* tcb_get_stack_top is declared in api/v4/tcb.h *after* it includes this
   header, so its one-line body is spelled out here too.  Keep the two in
   step -- the definition lives in glue/v4-powerpc64/thread.c. */
INLINE word_t * tcb_stack_top (tcb_t *tcb)
{
    /* Simon says : Evil? */
    return (word_t *) ((char *) tcb + KTCB_SIZE);
}

/* Every user-context accessor below reached for this same expression. */
INLINE powerpc64_irq_context_t * tcb_irq_context (tcb_t *tcb)
{
    return (powerpc64_irq_context_t *) tcb_stack_top (tcb) - 1;
}


/**********************************************************************
 *
 *                      thread switch routines
 *
 **********************************************************************/

/**
 * switch to initial thread
 * @param tcb TCB of initial thread
 *
 * Initializes context of initial thread and switches to it.  The
 * context (e.g., instruction pointer) has been generated by inserting
 * a notify procedure context on the stack.  We simply restore this
 * context.
 */
INLINE void NORETURN initial_switch_to (tcb_t * tcb)
{
#if CONFIG_POWERPC64_SLB
    word_t asr = space_get_vsid_asid (get_kernel_space ());
#elif CONFIG_POWERPC64_STAB
    word_t asr = ppc64_stab_get_asr (space_get_seg_table (get_kernel_space ()));
    asm volatile (
	"mfsprg	%%r7, %0;	"
	"std	%1, %2(%%r7);	"
	:: "i" (SPRG_LOCAL),
	   "r" (space_get_vsid_asid (get_kernel_space ())),
	   "i" (LOCAL_VSID_ASID)
	: "r7"
    );
#endif

    TRACEF("(%p), %p\n", tcb, tcb->stack);

    asm volatile (
	"mtsprg	%[tcb_sprg], %[tcb];"
	"mtasr	%[asr];	"
	"mr	%%r1, %[sp];	"
	"ld	%%r13, 32(%%r1);	"	/* Load func in temp1			*/
	"ld	%%r30, 40(%%r1);	"	/* Load arg1 in temp2			*/
	"ld	%%r31, 48(%%r1);	"	/* Load arg2 in temp3			*/
	"addi	%%r1, %%r1, 64;		"	/* Unstack the frame			*/
	"ld	%%r3, 16(%%r1);		"	/* Load the return address		*/
	"isync;				"
	"mtlr	%%r3;			"
	"blr;				"
	::
	[tcb] "r" (tcb),
	[sp] "r" (tcb->stack),
	[asr] "r" (asr),
	[tcb_sprg] "i" (SPRG_TCB)
    );

    while(true) {}
}


/**********************************************************************
 *
 *                        global tcb functions
 *
 **********************************************************************/
/**
 * Locate current TCB by using current stack pointer and return it.
 */
INLINE tcb_t * get_current_tcb (void)
{
    tcb_t * tcb;
    asm volatile (
	"mfsprg	%[tcb], %[tcb_sprg];"
	: [tcb] "=r" (tcb)
	: [tcb_sprg] "i" (SPRG_TCB)
    );
    return tcb;
}

#if defined(CONFIG_SMP)
INLINE cpuid_t get_current_cpu (void)
{
    /* was get_idle_tcb()->get_cpu().  This header is included from
       api/v4/tcb.h before tcb_get_cpu() and get_idle_tcb_c() are declared, so
       the idle tcb is reached directly -- as glue/v4-powerpc/tcb.h does. */
    return get_idle_tcb ()->cpu;
}
#endif


#endif /* !__GLUE__V4_POWERPC64__TCB_H__ */
