/*********************************************************************
 *
 * Copyright (C) 2006-2007,  Karlsruhe University
 *
 * File path:     arch/x86/x32/vmx_vmcs.h
 * Description:   Vanderpool Virtual Machine Extensions
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * $Id$
 *
 ********************************************************************/

#ifndef __ARCH__X86__VMX_H__
#define __ARCH__X86__VMX_H__

#include INC_ARCH_SA(cpu.h)
#include INC_GLUE(hwspace.h)

/**********************************************************************
 *
 *                  VMCS fields
 *
 * A VMCS is a hardware-managed page whose fields are reachable only through
 * VMREAD and VMWRITE, indexed by the VMCS_IDX_* encodings below.  Upstream
 * expressed that as a template, vmcs_field<index, T>, whose operator= and
 * operator T issued the VMWRITE/VMREAD -- so a VMCS field looked like a
 * struct member and every access checked, through `this', that the VMCS it
 * belonged to was the one currently loaded.  The empty field classes sat in
 * unions so that every member address equalled the object's own, which was the
 * VMCS physical address.
 *
 * In C the field name becomes a pair of accessors over an explicit vmcs_t *,
 * generated by the three macros below and named vmcs_<area>_get_<field> and
 * vmcs_<area>_set_<field>; `vmcs->gs.cr0 = x' is vmcs_gs_set_cr0 (vmcs, x).
 * The areas no longer nest -- they were unions at offset zero, so the area name
 * only ever documented which part of the VMCS a field belongs to, and it is
 * kept in the accessor name for exactly that.
 *
 **********************************************************************/

struct vmcs_t
{
    /* No members: the VMCS is not addressable memory.  sizeof is 1, as it was
       upstream (a union of unions of empty classes); vmcs_alloc_vmcs rounds up
       to the page the hardware requires. */
    char __opaque;
};
typedef struct vmcs_t vmcs_t;

/* Integer fields (word_t, u32_t, u16_t): a plain VMREAD/VMWRITE. */
#define VMCS_FIELD(area, name, index, type)					\
INLINE type vmcs_##area##_get_##name (vmcs_t *self)				\
{										\
    ASSERT (x86_vmptrtest ((u64_t) (word_t) self));				\
    return (type) x86_vmread (index);						\
}										\
INLINE void vmcs_##area##_set_##name (vmcs_t *self, type val)			\
{										\
    ASSERT (x86_vmptrtest ((u64_t) (word_t) self));				\
    x86_vmwrite (index, val);							\
}

/* 64-bit fields: two 32-bit halves, the high one at index | 1. */
#define VMCS_FIELD_U64(area, name, index)					\
INLINE u64_t vmcs_##area##_get_##name (vmcs_t *self)				\
{										\
    ASSERT (x86_vmptrtest ((u64_t) (word_t) self));				\
    return x86_vmread (index) | (((u64_t) x86_vmread (index | 0x1)) << 32);	\
}										\
INLINE void vmcs_##area##_set_##name (vmcs_t *self, u64_t val)			\
{										\
    ASSERT (x86_vmptrtest ((u64_t) (word_t) self));				\
    x86_vmwrite (index, (u32_t) val);						\
    x86_vmwrite (index | 0x1, (u32_t) (val >> 32));				\
}

/* Fields with a struct type: the template required a `raw' member and read and
   wrote through it, whatever its width.  __typeof__ keeps the narrowing where
   upstream had it instead of adding a cast per raw type. */
#define VMCS_FIELD_S(area, name, index, type)					\
INLINE type vmcs_##area##_get_##name (vmcs_t *self)				\
{										\
    type val;									\
    ASSERT (x86_vmptrtest ((u64_t) (word_t) self));				\
    val.raw = (__typeof__ (val.raw)) x86_vmread (index);			\
    return val;									\
}										\
INLINE void vmcs_##area##_set_##name (vmcs_t *self, type val)			\
{										\
    ASSERT (x86_vmptrtest ((u64_t) (word_t) self));				\
    x86_vmwrite (index, (word_t) val.raw);					\
}


/**********************************************************************
 *
 *                  VMCS segattr
 *
 **********************************************************************/

struct vmcs_segattr_t {
    union {
	u32_t raw;
	struct {
	    u32_t type :  4;
	    u32_t s    :  1;
	    u32_t dpl  :  2;
	    u32_t p    :  1;
	    u32_t mbz0 :  4;
	    u32_t avl  :  1;
	    u32_t l    :  1;
	    u32_t db   :  1;
	    u32_t g    :  1;
	    u32_t uu   :  1;
	    u32_t mbz1 : 15;
	} __attribute__((packed));
    };
};
typedef struct vmcs_segattr_t vmcs_segattr_t;

INLINE vmcs_segattr_t vmcs_segattr_new (void)
{ vmcs_segattr_t v; v.raw = 0; return v; }


/* Was vmcs_int_t::int_type_e.  The bitfield below is u32_t rather than the
   enum type: C enum bitfields have implementation-defined signedness, and the
   values are compared against these constants at the use sites anyway. */
enum vmcs_int_type_e {
    VMCS_INT_EXT_INT   = 0,
    VMCS_INT_HW_NMI    = 2,
    VMCS_INT_HW_EXCEPT = 3,
    VMCS_INT_SW_INT    = 4,
    VMCS_INT_SW_PRVLG  = 5,
    VMCS_INT_SW_EXCEPT = 6,
};

struct vmcs_int_t {
    union {
	u32_t raw;
	struct {
	    u32_t vector		:  8;
	    u32_t type			:  3;	/* vmcs_int_type_e */
	    bool err_code_valid		:  1;
	    bool nmi_unblock		:  1;
	    u32_t mbz0			: 18;
	    bool valid			:  1;
	} __attribute__((packed));
    };
};
typedef struct vmcs_int_t vmcs_int_t;

INLINE vmcs_int_t vmcs_int_new (void)
{ vmcs_int_t v; v.raw = 0; return v; }


/**********************************************************************
 *
 *                  VMX entry control
 *
 **********************************************************************/
/* 32-bit fields */
#define    VMCS_IDX_ENTRY_CTRL            0x4012
#define    VMCS_IDX_ENTRY_MSR_LD_COUNT    0x4014
#define    VMCS_IDX_ENTRY_IIF             0x4016
#define    VMCS_IDX_ENTRY_EXCEPT_ERR_CODE 0x4018
#define    VMCS_IDX_ENTRY_INSTR_LEN       0x401a

/* 64-bit fields */
#define    VMCS_IDX_ENTRY_MSR_LD_ADDR_F   0x200a
#define    VMCS_IDX_ENTRY_MSR_LD_ADDR_H   0x200b



struct vmcs_entryctr_t {
    union {
	u32_t raw;
	struct {
	    s32_t res0          :  9;
	    u32_t ia32e_mode    :  1;
	    u32_t entry_smm     :  1;
	    u32_t deact_dmt     :  1;
	    u32_t res1          : 20;
	} __attribute__((packed));
    };
};
typedef struct vmcs_entryctr_t vmcs_entryctr_t;

INLINE vmcs_entryctr_t vmcs_entryctr_new (void)
{ vmcs_entryctr_t v; v.raw = (u32_t) x86_rdmsr (X86_MSR_VMX_ENTRY_CTLS); return v; }


struct vmcs_entryctr_eec_t {
    union {
	u32_t raw;
	u32_t ecode;
    };
};
typedef struct vmcs_entryctr_eec_t vmcs_entryctr_eec_t;

INLINE vmcs_entryctr_eec_t vmcs_entryctr_eec_new (void)
{ vmcs_entryctr_eec_t v; v.raw = 0; return v; }


/**********************************************************************
 *
 *                  VMX execution control
 *
 **********************************************************************/

/* 32-bit fields */
#define    VMCS_IDX_PIN_BASED_VM_EXEC_CTRL   0x4000
#define    VMCS_IDX_CPU_BASED_VM_EXEC_CTRL   0x4002
#define    VMCS_IDX_EXCEPTION_BITMAP         0x4004
#define    VMCS_IDX_PF_ERR_CODE_MASK         0x4006
#define    VMCS_IDX_PF_ERR_CODE_MATCH        0x4008
#define    VMCS_IDX_CR3_TARGET_COUNT         0x400a
#define    VMCS_IDX_TPR_THRESHOLD            0x401c

/* 64-bit fields */
#define    VMCS_IDX_IO_BITMAP_A_F            0x2000
#define    VMCS_IDX_IO_BITMAP_A_H            0x2001
#define    VMCS_IDX_IO_BITMAP_B_F            0x2002
#define    VMCS_IDX_IO_BITMAP_B_H            0x2003
#define    VMCS_IDX_TSC_OFF_F                0x2010
#define    VMCS_IDX_TSC_OFF_H                0x2011
#define    VMCS_IDX_VAPIC_PAGE_ADDR_F        0x2012
#define    VMCS_IDX_VAPIC_PAGE_ADDR_H        0x2013

/* Word size fields */
#define    VMCS_IDX_CR0_MASK                 0x6000
#define    VMCS_IDX_CR4_MASK                 0x6002
#define    VMCS_IDX_CR0_SHADOW               0x6004
#define    VMCS_IDX_CR4_SHADOW               0x6006
#define    VMCS_IDX_CR3_VAL_0                0x6008
#define    VMCS_IDX_CR3_VAL_1                0x600a
#define    VMCS_IDX_CR3_VAL_2                0x600c
#define    VMCS_IDX_CR3_VAL_3                0x600e


struct vmcs_exectr_pinbased_t {
    union {
	u32_t raw;
	struct {
	    s32_t extint_exit   :  1;
	    s32_t res1          :  2;
	    s32_t nmi_exit      :  1;
	    s32_t res2          : 28;
	} __attribute__((packed));
    };
};
typedef struct vmcs_exectr_pinbased_t vmcs_exectr_pinbased_t;

INLINE vmcs_exectr_pinbased_t vmcs_exectr_pinbased_new (void)
{
    vmcs_exectr_pinbased_t v;
    v.raw	  = (u32_t) x86_rdmsr (X86_MSR_VMX_PINBASED_CTLS);
    v.extint_exit = 1;
    v.nmi_exit	  = 1;
    return v;
}


struct vmcs_exectr_cpubased_t {
    union {
	u32_t raw;
	struct {
	    s32_t res0          : 2;
	    u32_t iw            : 1;
	    u32_t tscoff        : 1;
	    u32_t res1          : 3;
	    u32_t hlt           : 1;
	    s32_t res2          : 1;
	    u32_t invlpg        : 1;
	    u32_t mwait         : 1;
	    u32_t rdpmc         : 1;
	    u32_t rdtsc         : 1;
	    s32_t res3          : 6;
	    u32_t lcr8          : 1;
	    u32_t scr8          : 1;
	    u32_t tpr_shadow    : 1;
	    s32_t res4          : 1;
	    u32_t movdr         : 1;
	    u32_t io            : 1;
	    u32_t iobitm        : 1;
	    s32_t res5          : 2;
	    u32_t msrbitm	: 1;
	    u32_t monitor       : 1;
	    u32_t pause         : 1;
	    s32_t res6          : 1;
	} __attribute__((packed));
    };
};
typedef struct vmcs_exectr_cpubased_t vmcs_exectr_cpubased_t;

INLINE vmcs_exectr_cpubased_t vmcs_exectr_cpubased_new (void)
{
    vmcs_exectr_cpubased_t v;
    v.raw	= (u32_t) x86_rdmsr (X86_MSR_VMX_CPUBASED_CTLS);
    v.hlt	= 1;
    v.invlpg	= 1;
    v.mwait	= 1;
    v.rdpmc	= 1;
    v.rdtsc	= 1;
    v.movdr	= 1;
    v.monitor	= 1;
    v.pause	= 1;
    v.io	= 1;
    return v;
}


struct vmcs_exectr_excbmp_t {
    union {
	s32_t raw;
	struct {
	    u32_t de		: 1;
	    u32_t db		: 1;
	    u32_t nmi		: 1;
	    u32_t bp		: 1;
	    u32_t of		: 1;
	    u32_t br		: 1;
	    u32_t ud		: 1;
	    u32_t nm		: 1;
	    u32_t df		: 1;
	    u32_t copseg_overrun: 1;
	    u32_t ts		: 1;
	    u32_t np		: 1;
	    u32_t ss		: 1;
	    u32_t gp		: 1;
	    u32_t pf		: 1;
	    u32_t _reserved	: 1;
	    u32_t mf		: 1;
	    u32_t ac		: 1;
	    u32_t mc		: 1;
	    u32_t xf		: 1;
	    u32_t high		:12;
	} __attribute__((packed));
    };
};
typedef struct vmcs_exectr_excbmp_t vmcs_exectr_excbmp_t;

INLINE vmcs_exectr_excbmp_t vmcs_exectr_excbmp_new (void)
{ vmcs_exectr_excbmp_t v; v.raw = -1; return v; }


struct vmcs_exectr_tprth_t {
    union {
	u32_t raw;
	struct {
	    u32_t th            :  4;
	    u32_t reserved      : 28;
	} __attribute__((packed));
    };
};
typedef struct vmcs_exectr_tprth_t vmcs_exectr_tprth_t;

INLINE vmcs_exectr_tprth_t vmcs_exectr_tprth_new (void)
{ vmcs_exectr_tprth_t v; v.raw = 0; return v; }


/**********************************************************************
 *
 *                  VMX exit control
 *
 **********************************************************************/

/* 32-bit fields */
#define    VMCS_IDX_EXIT_CTRL             0x400c
#define    VMCS_IDX_EXIT_MSR_ST_COUNT     0x400e
#define    VMCS_IDX_EXIT_MSR_LD_COUNT     0x4010

/* 64-bit fields */
#define    VMCS_IDX_EXIT_MSR_ST_ADDR_F    0x2006
#define    VMCS_IDX_EXIT_MSR_ST_ADDR_H    0x2007
#define    VMCS_IDX_EXIT_MSR_LD_ADDR_F    0x2008
#define    VMCS_IDX_EXIT_MSR_LD_ADDR_H    0x2009


struct vmcs_exitctr_t {
    union {
	u32_t raw;
	struct {
	    s32_t res0          :  9;
	    u32_t host_as_sz    :  1;
	    s32_t res1          :  5;
	    u32_t ack_int       :  1;
	    u32_t res2          : 16;
	} __attribute__((packed));
    };
};
typedef struct vmcs_exitctr_t vmcs_exitctr_t;

INLINE vmcs_exitctr_t vmcs_exitctr_new (void)
{ vmcs_exitctr_t v; v.raw = (u32_t) x86_rdmsr (X86_MSR_VMX_EXIT_CTLS); return v; }


/**********************************************************************
 *
 *                  VMX exit info
 *
 **********************************************************************/

/* 32-bit fields */
#define    VMCS_IDX_EINFO_VM_INSTR_ERROR           0x4400
#define    VMCS_IDX_EINFO_EXIT_REASON		   0x4402
#define    VMCS_IDX_EINFO_INTERRUPTION_INFO        0x4404
#define    VMCS_IDX_EINFO_INTERRUPTION_ERROR_CODE  0x4406
#define    VMCS_IDX_EINFO_IDT_VECTORING_INFO       0x4408
#define    VMCS_IDX_EINFO_IDT_VECTORING_ERROR_CODE 0x440a
#define    VMCS_IDX_EINFO_INSTR_LEN                0x440c
#define    VMCS_IDX_EINFO_VM_INSTR_INFO            0x440e

/* Word size fields */
#define    VMCS_IDX_EINFO_EXIT_QUAL          0x6400
#define    VMCS_IDX_EINFO_GUEST_LIN_ADDR     0x640A


/* Was vmcs_ei_reason_t::basic_reason_e. */
enum vmcs_basic_reason_e {
    VMCS_BE_EXP_NMI      =  0,
    VMCS_BE_EXT_INT      =  1,
    VMCS_BE_TF           =  2,
    VMCS_BE_INIT         =  3,
    VMCS_BE_SIPI         =  4,
    VMCS_BE_SMI          =  6,
    VMCS_BE_IW           =  7,
    VMCS_BE_TASKSW       =  9,
    VMCS_BE_CPUID        = 10,
    VMCS_BE_HLT          = 12,
    VMCS_BE_INVD         = 13,
    VMCS_BE_INVLPG       = 14,
    VMCS_BE_RDPMC        = 15,
    VMCS_BE_RDTSC        = 16,
    VMCS_BE_RSM          = 17,
    VMCS_BE_VMCALL       = 18,
    VMCS_BE_VMCLEAR      = 19,
    VMCS_BE_VMLAUNCH     = 20,
    VMCS_BE_VMPTRLD      = 21,
    VMCS_BE_VMPTRST      = 22,
    VMCS_BE_VMREAD       = 23,
    VMCS_BE_VMRESUME     = 24,
    VMCS_BE_VMWRITE      = 25,
    VMCS_BE_VMXOFF       = 26,
    VMCS_BE_VMXON        = 27,
    VMCS_BE_CR           = 28,
    VMCS_BE_DR           = 29,
    VMCS_BE_IO           = 30,
    VMCS_BE_RDMSR        = 31,
    VMCS_BE_WRMSR        = 32,
    VMCS_BE_ENTRY_INVG   = 33,
    VMCS_BE_ENTRY_MSRLD  = 34,
    VMCS_BE_MWAIT        = 36,
    VMCS_BE_MONITOR      = 39,
    VMCS_BE_PAUSE        = 40,
    VMCS_BE_ENTRY_MCE    = 41,
    VMCS_BE_ENTRY_TPRTSH = 43,
    VMCS_BE_MAX
};

/* Was vmcs_ei_reason_t::vm_instr_err_e. */
enum vmcs_vm_instr_err_e {
    VMCS_IE_VMCALL       =  1,
    VMCS_IE_VMCLEAR1     =  2,
    VMCS_IE_VMCLEAR2     =  3,
    VMCS_IE_VMLAUNCH     =  4,
    VMCS_IE_VMRESUME1    =  5,
    VMCS_IE_VMRESUME2    =  6,
    VMCS_IE_VMENTRY1     =  7,
    VMCS_IE_VMENTRY2     =  8,
    VMCS_IE_VMPTRLD1     =  9,
    VMCS_IE_VMPTRLD2     = 10,
    VMCS_IE_VMPTRLD3     = 11,
    VMCS_IE_VMRDWR       = 12,
    VMCS_IE_VMWR         = 13,
    VMCS_IE_VMENTRY3     = 26,
};

struct vmcs_ei_reason_t {
    union {
	u32_t raw;
	struct {
	    u32_t basic_reason          : 16;	/* vmcs_basic_reason_e */
	    u32_t mbz0                  : 13;
	    bool  exit_vmx_root_op      :  1;
	    u32_t mbz1                  :  1;
	    bool is_entry_fail          :  1;
	} __attribute__((packed));
    };
};
typedef struct vmcs_ei_reason_t vmcs_ei_reason_t;

INLINE vmcs_ei_reason_t vmcs_ei_reason_new (void)
{ vmcs_ei_reason_t v; v.raw = 0; return v; }


/*
 * Was the nested enums of vmcs_ei_vm_instr_t and vmcs_ei_qual_t.  gpr_e and
 * mem_reg_e were declared identically in both, so one copy of each serves.
 */
enum vmcs_gpr_e {
    VMCS_GPR_RAX =  0, VMCS_GPR_RCX =  1, VMCS_GPR_RDX =  2, VMCS_GPR_RBX =  3,
    VMCS_GPR_RSP =  4, VMCS_GPR_RBP =  5, VMCS_GPR_RSI =  6, VMCS_GPR_RDI =  7,
    VMCS_GPR_R8  =  8, VMCS_GPR_R9  =  9, VMCS_GPR_R10 = 10, VMCS_GPR_R11 = 11,
    VMCS_GPR_R12 = 12, VMCS_GPR_R13 = 13, VMCS_GPR_R14 = 14, VMCS_GPR_R15 = 15,
};

enum vmcs_mem_reg_e	{ VMCS_MEM = 0, VMCS_REG = 1 };
enum vmcs_scaling_e	{ VMCS_SCALE0 = 0, VMCS_SCALE2 = 1, VMCS_SCALE4 = 2, VMCS_SCALE8 = 3 };
enum vmcs_addr_sz_e	{ VMCS_ADDRSZ_BIT16 = 0, VMCS_ADDRSZ_BIT32 = 1, VMCS_ADDRSZ_BIT64 = 2 };
enum vmcs_seg_reg_e	{ VMCS_SEGREG_ES = 0, VMCS_SEGREG_CS = 1, VMCS_SEGREG_SS = 2,
			  VMCS_SEGREG_DS = 3, VMCS_SEGREG_FS = 4, VMCS_SEGREG_GS = 5 };
enum vmcs_source_of_tss_e { VMCS_TSS_CALL = 0, VMCS_TSS_IRET = 1, VMCS_TSS_JMP = 2,
			    VMCS_TSS_TASK_GATE = 3 };
enum vmcs_soa_e		{ VMCS_SOA_U8 = 0, VMCS_SOA_U16 = 1, VMCS_SOA_U32 = 3 };
enum vmcs_access_type_e	{ VMCS_ACC_TO_CR = 0, VMCS_ACC_FROM_CR = 1, VMCS_ACC_CLTS = 2,
			  VMCS_ACC_LMSW = 3 };
enum vmcs_dir_e		{ VMCS_DIR_OUT = 0, VMCS_DIR_IN = 1 };
enum vmcs_op_encoding_e	{ VMCS_OPENC_DX = 0, VMCS_OPENC_IMMEDIATE = 1 };


struct vmcs_ei_vm_instr_t {
    union {
	u32_t raw;
	struct {
	    u32_t	scaling	      :  2;   /* vmcs_scaling_e */
	    u32_t	mbz0          :  1;
	    u32_t	reg1          :  4;   /* vmcs_gpr_e */
	    u32_t	ad66dr_sz     :  3;   /* vmcs_addr_sz_e */
	    u32_t	mem_reg       :  1;   /* vmcs_mem_reg_e */
	    u32_t	mbz1	      :  4;
	    u32_t	seg_reg       :  3;   /* vmcs_seg_reg_e */
	    u32_t	idx_reg       :  4;   /* vmcs_gpr_e */
	    bool	idx_reg_inv   :  1;
	    u32_t	base_reg      :  4;   /* vmcs_gpr_e */
	    bool	base_reg_inv  :  1;
	    u32_t	reg2          :  4;   /* vmcs_gpr_e */
	};
    };
};
typedef struct vmcs_ei_vm_instr_t vmcs_ei_vm_instr_t;

INLINE vmcs_ei_vm_instr_t vmcs_ei_vm_instr_new (void)
{ vmcs_ei_vm_instr_t v; v.raw = 0; return v; }


struct vmcs_ei_qual_t {
    union {
	word_t raw;

	// Page Fault Address.
	word_t faddr;

	struct {
	    u32_t bx            :  4;
	    u32_t mbz0          :  9;
	    u32_t bd            :  1;
	    u32_t bs            :  1;
	    u32_t res           : 17;
	} __attribute__((packed)) dbg;
	struct {
	    u32_t	selector      : 16;
	    u32_t	mbz0          : 14;
	    u32_t	source        :  2;   /* vmcs_source_of_tss_e */
	} __attribute__((packed)) task_sw;
	struct {
	    u32_t	cr_num        :  4;
	    u32_t	access_type   :  2;   /* vmcs_access_type_e */
	    u32_t	lmsw_op_type  :  1;   /* vmcs_mem_reg_e */
	    u32_t	mbz0          :  1;
	    u32_t	mov_cr_gpr    :  4;   /* vmcs_gpr_e */
	    u32_t	mbz1          :  4;
	    u32_t	lmsw_src_data : 16;
	} __attribute__((packed)) mov_cr;
	struct {
	    u32_t	dr_num        :  3;
	    u32_t	mbz0          :  1;
	    u32_t	dir           :  1;
	    u32_t	mbz1          :  3;
	    u32_t	mov_dr_gpr    :  4;   /* vmcs_gpr_e */
	    u32_t	mbz2	      : 20;
	} __attribute__((packed)) mov_dr;
	struct {
	    u32_t	soa	      :  3;   /* vmcs_soa_e */
	    u32_t	dir           :  1;   /* vmcs_dir_e */
	    bool	string        :  1;
	    bool	rep           :  1;
	    u32_t	op_encoding   :  1;   /* vmcs_op_encoding_e */
	    u32_t	mbz0          :  9;
	    u32_t	port_num      : 16;
	} __attribute__((packed)) io;
    };
};
typedef struct vmcs_ei_qual_t vmcs_ei_qual_t;

INLINE vmcs_ei_qual_t vmcs_ei_qual_new (void)
{ vmcs_ei_qual_t v; v.raw = 0; return v; }


/**********************************************************************
 *
 *                  VMX guest state
 *
 **********************************************************************/

/* 16-bit fields */
#define    VMCS_IDX_G_ES_SEL           0x0800
#define    VMCS_IDX_G_CS_SEL           0x0802
#define    VMCS_IDX_G_SS_SEL           0x0804
#define    VMCS_IDX_G_DS_SEL           0x0806
#define    VMCS_IDX_G_FS_SEL           0x0808
#define    VMCS_IDX_G_GS_SEL           0x080a
#define    VMCS_IDX_G_LDTR_SEL         0x080c
#define    VMCS_IDX_G_TR_SEL           0x080e

/* 32-bit fields */
#define    VMCS_IDX_G_ES_LIMIT         0x4800
#define    VMCS_IDX_G_CS_LIMIT         0x4802
#define    VMCS_IDX_G_SS_LIMIT         0x4804
#define    VMCS_IDX_G_DS_LIMIT         0x4806
#define    VMCS_IDX_G_FS_LIMIT         0x4808
#define    VMCS_IDX_G_GS_LIMIT         0x480a
#define    VMCS_IDX_G_LDTR_LIMIT       0x480c
#define    VMCS_IDX_G_TR_LIMIT         0x480e
#define    VMCS_IDX_G_GDTR_LIMIT       0x4810
#define    VMCS_IDX_G_IDTR_LIMIT       0x4812
#define    VMCS_IDX_G_ES_ATTR          0x4814
#define    VMCS_IDX_G_CS_ATTR          0x4816
#define    VMCS_IDX_G_SS_ATTR          0x4818
#define    VMCS_IDX_G_DS_ATTR          0x481a
#define    VMCS_IDX_G_FS_ATTR          0x481c
#define    VMCS_IDX_G_GS_ATTR          0x481e
#define    VMCS_IDX_G_LDTR_ATTR        0x4820
#define    VMCS_IDX_G_TR_ATTR          0x4822
#define    VMCS_IDX_G_INTR_ABILITY_STATE  0x4824
#define    VMCS_IDX_G_ACTIVITY_STATE   0x4826
#define    VMCS_IDX_G_SYSENTER_CS      0x482a

/* 64-bit fields */
#define    VMCS_IDX_G_VMCS_LINK_PTR_F  0x2800
#define    VMCS_IDX_G_VMCS_LINK_PTR_H  0x2801
#define    VMCS_IDX_G_DEBUGCTL_F       0x2802
#define    VMCS_IDX_G_DEBUGCTL_H       0x2803

/* Word size fields */
#define    VMCS_IDX_G_CR0              0x6800
#define    VMCS_IDX_G_CR3              0x6802
#define    VMCS_IDX_G_CR4              0x6804
#define    VMCS_IDX_G_ES_BASE          0x6806
#define    VMCS_IDX_G_CS_BASE          0x6808
#define    VMCS_IDX_G_SS_BASE          0x680a
#define    VMCS_IDX_G_DS_BASE          0x680c
#define    VMCS_IDX_G_FS_BASE          0x680e
#define    VMCS_IDX_G_GS_BASE          0x6810
#define    VMCS_IDX_G_LDTR_BASE        0x6812
#define    VMCS_IDX_G_TR_BASE          0x6814
#define    VMCS_IDX_G_GDTR_BASE        0x6816
#define    VMCS_IDX_G_IDTR_BASE        0x6818
#define    VMCS_IDX_G_DR7              0x681a
#define    VMCS_IDX_G_RSP              0x681c
#define    VMCS_IDX_G_RIP              0x681e
#define    VMCS_IDX_G_RFLAGS           0x6820
#define    VMCS_IDX_G_PEND_DBG_EXCEPT  0x6822
#define    VMCS_IDX_G_SYSENTER_ESP     0x6824
#define    VMCS_IDX_G_SYSENTER_EIP     0x6826

struct vmcs_gs_ias_t {
    union {
	u32_t raw;
	struct {
	    u32_t bl_sti        :  1;
	    u32_t bl_movss      :  1;
	    u32_t bl_smi        :  1;
	    u32_t bl_nmi        :  1;
	    u32_t mbz0          : 28;
	} __attribute__((packed));
    } ;
};
typedef struct vmcs_gs_ias_t vmcs_gs_ias_t;

INLINE vmcs_gs_ias_t vmcs_gs_ias_new (void)
{ vmcs_gs_ias_t v; v.raw = 0; return v; }


/* Was vmcs_gs_as_t::vmcs_gs_as_e. */
enum vmcs_gs_as_e {
    VMCS_AS_ACTIVE = 0UL, VMCS_AS_HLT = 1UL, VMCS_AS_SHUTDOWN = 2UL,
    VMCS_AS_WF_IPI = 3UL,
};

struct vmcs_gs_as_t {
    union {
	u32_t raw;
	u32_t state;			/* vmcs_gs_as_e */
    };
};
typedef struct vmcs_gs_as_t vmcs_gs_as_t;

INLINE vmcs_gs_as_t vmcs_gs_as_new (void)
{ vmcs_gs_as_t v; v.raw = 0; return v; }


struct vmcs_gs_pend_dbg_except_t {
    union {
	u64_t raw;
	struct {
	    u64_t bx    :  4;
	    u64_t mbz0  :  8;
	    u64_t br    :  1;
	    u64_t mbz1  :  1;
	    u64_t bs    :  1;
	    u64_t mbz2  : 49;
	} __attribute__((packed));
    };
};
typedef struct vmcs_gs_pend_dbg_except_t vmcs_gs_pend_dbg_except_t;

INLINE vmcs_gs_pend_dbg_except_t vmcs_gs_pend_dbg_except_new (void)
{ vmcs_gs_pend_dbg_except_t v; v.raw = 0; return v; }


/**********************************************************************
 *
 *                  VMX host state
 *
 **********************************************************************/

/* 16-bit fields */
#define    VMCS_IDX_H_ES_SEL           0x0c00
#define    VMCS_IDX_H_CS_SEL           0x0c02
#define    VMCS_IDX_H_SS_SEL           0x0c04
#define    VMCS_IDX_H_DS_SEL           0x0c06
#define    VMCS_IDX_H_FS_SEL           0x0c08
#define    VMCS_IDX_H_GS_SEL           0x0c0a
#define    VMCS_IDX_H_TR_SEL           0x0c0c

/* 32-bit fields */
#define    VMCS_IDX_H_SYSENTER_CS      0x4c00

/* Word size fields */
#define    VMCS_IDX_H_CR0              0x6c00
#define    VMCS_IDX_H_CR3              0x6c02
#define    VMCS_IDX_H_CR4              0x6c04
#define    VMCS_IDX_H_FS_BASE          0x6c06
#define    VMCS_IDX_H_GS_BASE          0x6c08
#define    VMCS_IDX_H_TR_BASE          0x6c0a
#define    VMCS_IDX_H_GDTR_BASE        0x6c0c
#define    VMCS_IDX_H_IDTR_BASE        0x6c0e
#define    VMCS_IDX_H_SYSENTER_ESP     0x6c10
#define    VMCS_IDX_H_SYSENTER_EIP     0x6c12
#define    VMCS_IDX_H_RSP              0x6c14
#define    VMCS_IDX_H_RIP              0x6c16


/**********************************************************************
 *
 *                  VMCS field accessors
 *
 **********************************************************************/

/*******************************************************
 *
 * Guest State Area
 *
 *******************************************************/
VMCS_FIELD      (gs, es_sel,          VMCS_IDX_G_ES_SEL,                         u16_t)
VMCS_FIELD      (gs, cs_sel,          VMCS_IDX_G_CS_SEL,                         u16_t)
VMCS_FIELD      (gs, ss_sel,          VMCS_IDX_G_SS_SEL,                         u16_t)
VMCS_FIELD      (gs, ds_sel,          VMCS_IDX_G_DS_SEL,                         u16_t)
VMCS_FIELD      (gs, fs_sel,          VMCS_IDX_G_FS_SEL,                         u16_t)
VMCS_FIELD      (gs, gs_sel,          VMCS_IDX_G_GS_SEL,                         u16_t)
VMCS_FIELD      (gs, ldtr_sel,        VMCS_IDX_G_LDTR_SEL,                       u16_t)
VMCS_FIELD      (gs, tr_sel,          VMCS_IDX_G_TR_SEL,                         u16_t)
VMCS_FIELD      (gs, es_base,         VMCS_IDX_G_ES_BASE,                        word_t)
VMCS_FIELD      (gs, cs_base,         VMCS_IDX_G_CS_BASE,                        word_t)
VMCS_FIELD      (gs, ss_base,         VMCS_IDX_G_SS_BASE,                        word_t)
VMCS_FIELD      (gs, ds_base,         VMCS_IDX_G_DS_BASE,                        word_t)
VMCS_FIELD      (gs, fs_base,         VMCS_IDX_G_FS_BASE,                        word_t)
VMCS_FIELD      (gs, gs_base,         VMCS_IDX_G_GS_BASE,                        word_t)
VMCS_FIELD      (gs, ldtr_base,       VMCS_IDX_G_LDTR_BASE,                      word_t)
VMCS_FIELD      (gs, tr_base,         VMCS_IDX_G_TR_BASE,                        word_t)
VMCS_FIELD      (gs, gdtr_base,       VMCS_IDX_G_GDTR_BASE,                      word_t)
VMCS_FIELD      (gs, idtr_base,       VMCS_IDX_G_IDTR_BASE,                      word_t)
VMCS_FIELD      (gs, es_lim,          VMCS_IDX_G_ES_LIMIT,                       u32_t)
VMCS_FIELD      (gs, cs_lim,          VMCS_IDX_G_CS_LIMIT,                       u32_t)
VMCS_FIELD      (gs, ss_lim,          VMCS_IDX_G_SS_LIMIT,                       u32_t)
VMCS_FIELD      (gs, ds_lim,          VMCS_IDX_G_DS_LIMIT,                       u32_t)
VMCS_FIELD      (gs, fs_lim,          VMCS_IDX_G_FS_LIMIT,                       u32_t)
VMCS_FIELD      (gs, gs_lim,          VMCS_IDX_G_GS_LIMIT,                       u32_t)
VMCS_FIELD      (gs, ldtr_lim,        VMCS_IDX_G_LDTR_LIMIT,                     u32_t)
VMCS_FIELD      (gs, tr_lim,          VMCS_IDX_G_TR_LIMIT,                       u32_t)
VMCS_FIELD      (gs, gdtr_lim,        VMCS_IDX_G_GDTR_LIMIT,                     u32_t)
VMCS_FIELD      (gs, idtr_lim,        VMCS_IDX_G_IDTR_LIMIT,                     u32_t)
VMCS_FIELD_S    (gs, es_attr,         VMCS_IDX_G_ES_ATTR,                        vmcs_segattr_t)
VMCS_FIELD_S    (gs, cs_attr,         VMCS_IDX_G_CS_ATTR,                        vmcs_segattr_t)
VMCS_FIELD_S    (gs, ss_attr,         VMCS_IDX_G_SS_ATTR,                        vmcs_segattr_t)
VMCS_FIELD_S    (gs, ds_attr,         VMCS_IDX_G_DS_ATTR,                        vmcs_segattr_t)
VMCS_FIELD_S    (gs, fs_attr,         VMCS_IDX_G_FS_ATTR,                        vmcs_segattr_t)
VMCS_FIELD_S    (gs, gs_attr,         VMCS_IDX_G_GS_ATTR,                        vmcs_segattr_t)
VMCS_FIELD_S    (gs, ldtr_attr,       VMCS_IDX_G_LDTR_ATTR,                      vmcs_segattr_t)
VMCS_FIELD_S    (gs, tr_attr,         VMCS_IDX_G_TR_ATTR,                        vmcs_segattr_t)
VMCS_FIELD_S    (gs, ias,             VMCS_IDX_G_INTR_ABILITY_STATE,             vmcs_gs_ias_t)
VMCS_FIELD_S    (gs, as,              VMCS_IDX_G_ACTIVITY_STATE,                 vmcs_gs_as_t)
VMCS_FIELD_U64  (gs, linkptr,         VMCS_IDX_G_VMCS_LINK_PTR_F)
VMCS_FIELD_U64  (gs, dbg_ctl,         VMCS_IDX_G_DEBUGCTL_F)
VMCS_FIELD      (gs, cr0,             VMCS_IDX_G_CR0,                            word_t)
VMCS_FIELD      (gs, cr3,             VMCS_IDX_G_CR3,                            word_t)
VMCS_FIELD      (gs, cr4,             VMCS_IDX_G_CR4,                            word_t)
VMCS_FIELD      (gs, dr7,             VMCS_IDX_G_DR7,                            word_t)
VMCS_FIELD      (gs, rsp,             VMCS_IDX_G_RSP,                            word_t)
VMCS_FIELD      (gs, rip,             VMCS_IDX_G_RIP,                            word_t)
VMCS_FIELD      (gs, rflags,          VMCS_IDX_G_RFLAGS,                         word_t)
VMCS_FIELD_S    (gs, pend_dbg_except, VMCS_IDX_G_PEND_DBG_EXCEPT,                vmcs_gs_pend_dbg_except_t)
VMCS_FIELD      (gs, sysenter_cs,     VMCS_IDX_G_SYSENTER_CS,                    u32_t)
VMCS_FIELD      (gs, sysenter_esp,    VMCS_IDX_G_SYSENTER_ESP,                   word_t)
VMCS_FIELD      (gs, sysenter_eip,    VMCS_IDX_G_SYSENTER_EIP,                   word_t)

/*******************************************************
 *
 * Host State Area
 *
 *******************************************************/
VMCS_FIELD      (hs, es_sel,          VMCS_IDX_H_ES_SEL,                         u16_t)
VMCS_FIELD      (hs, cs_sel,          VMCS_IDX_H_CS_SEL,                         u16_t)
VMCS_FIELD      (hs, ss_sel,          VMCS_IDX_H_SS_SEL,                         u16_t)
VMCS_FIELD      (hs, ds_sel,          VMCS_IDX_H_DS_SEL,                         u16_t)
VMCS_FIELD      (hs, fs_sel,          VMCS_IDX_H_FS_SEL,                         u16_t)
VMCS_FIELD      (hs, gs_sel,          VMCS_IDX_H_GS_SEL,                         u16_t)
VMCS_FIELD      (hs, tr_sel,          VMCS_IDX_H_TR_SEL,                         u16_t)
VMCS_FIELD      (hs, fs_base,         VMCS_IDX_H_FS_BASE,                        word_t)
VMCS_FIELD      (hs, gs_base,         VMCS_IDX_H_GS_BASE,                        word_t)
VMCS_FIELD      (hs, tr_base,         VMCS_IDX_H_TR_BASE,                        word_t)
VMCS_FIELD      (hs, gdtr_base,       VMCS_IDX_H_GDTR_BASE,                      word_t)
VMCS_FIELD      (hs, idtr_base,       VMCS_IDX_H_IDTR_BASE,                      word_t)
VMCS_FIELD      (hs, sysenter_cs,     VMCS_IDX_H_SYSENTER_CS,                    u32_t)
VMCS_FIELD      (hs, sysenter_esp,    VMCS_IDX_H_SYSENTER_ESP,                   word_t)
VMCS_FIELD      (hs, sysenter_eip,    VMCS_IDX_H_SYSENTER_EIP,                   word_t)
VMCS_FIELD      (hs, rsp,             VMCS_IDX_H_RSP,                            word_t)
VMCS_FIELD      (hs, rip,             VMCS_IDX_H_RIP,                            word_t)
VMCS_FIELD      (hs, cr0,             VMCS_IDX_H_CR0,                            word_t)
VMCS_FIELD      (hs, cr3,             VMCS_IDX_H_CR3,                            word_t)
VMCS_FIELD      (hs, cr4,             VMCS_IDX_H_CR4,                            word_t)

/*******************************************************
 *
 * VM Exec Control Area
 *
 *******************************************************/
VMCS_FIELD_S    (exec_ctr, pinbased,        VMCS_IDX_PIN_BASED_VM_EXEC_CTRL,           vmcs_exectr_pinbased_t)
VMCS_FIELD_S    (exec_ctr, cpubased,        VMCS_IDX_CPU_BASED_VM_EXEC_CTRL,           vmcs_exectr_cpubased_t)
VMCS_FIELD_S    (exec_ctr, except_bmp,      VMCS_IDX_EXCEPTION_BITMAP,                 vmcs_exectr_excbmp_t)
VMCS_FIELD      (exec_ctr, pferrmask,       VMCS_IDX_PF_ERR_CODE_MASK,                 u32_t)
VMCS_FIELD      (exec_ctr, pferrmatch,      VMCS_IDX_PF_ERR_CODE_MATCH,                u32_t)
VMCS_FIELD_S    (exec_ctr, tprthr,          VMCS_IDX_TPR_THRESHOLD,                    vmcs_exectr_tprth_t)
VMCS_FIELD_U64  (exec_ctr, iobmpa,          VMCS_IDX_IO_BITMAP_A_F)
VMCS_FIELD_U64  (exec_ctr, iobmpb,          VMCS_IDX_IO_BITMAP_B_F)
VMCS_FIELD_U64  (exec_ctr, tscoff,          VMCS_IDX_TSC_OFF_F)
VMCS_FIELD_U64  (exec_ctr, vapicaddr,       VMCS_IDX_VAPIC_PAGE_ADDR_F)
VMCS_FIELD      (exec_ctr, cr0mask,         VMCS_IDX_CR0_MASK,                         word_t)
VMCS_FIELD      (exec_ctr, cr4mask,         VMCS_IDX_CR4_MASK,                         word_t)
VMCS_FIELD      (exec_ctr, cr0shadow,       VMCS_IDX_CR0_SHADOW,                       word_t)
VMCS_FIELD      (exec_ctr, cr4shadow,       VMCS_IDX_CR4_SHADOW,                       word_t)
VMCS_FIELD      (exec_ctr, cr3targetcnt,    VMCS_IDX_CR3_TARGET_COUNT,                 u32_t)
VMCS_FIELD      (exec_ctr, cr3val0,         VMCS_IDX_CR3_VAL_0,                        word_t)
VMCS_FIELD      (exec_ctr, cr3val1,         VMCS_IDX_CR3_VAL_1,                        word_t)
VMCS_FIELD      (exec_ctr, cr3val2,         VMCS_IDX_CR3_VAL_2,                        word_t)
VMCS_FIELD      (exec_ctr, cr3val3,         VMCS_IDX_CR3_VAL_3,                        word_t)

/*******************************************************
 *
 * VM Exit Control Area
 *
 *******************************************************/
VMCS_FIELD_S    (exit_ctr, exitctr,         VMCS_IDX_EXIT_CTRL,                        vmcs_exitctr_t)
VMCS_FIELD      (exit_ctr, msr_st_cnt,      VMCS_IDX_EXIT_MSR_ST_COUNT,                u32_t)
VMCS_FIELD      (exit_ctr, msr_ld_cnt,      VMCS_IDX_EXIT_MSR_LD_COUNT,                u32_t)
VMCS_FIELD_U64  (exit_ctr, msr_st_addr,     VMCS_IDX_EXIT_MSR_ST_ADDR_F)
VMCS_FIELD_U64  (exit_ctr, msr_ld_addr,     VMCS_IDX_EXIT_MSR_LD_ADDR_F)

/*******************************************************
 *
 * VM Entry Control Area
 *
 *******************************************************/
VMCS_FIELD_S    (entry_ctr, entryctr,        VMCS_IDX_ENTRY_CTRL,                       vmcs_entryctr_t)
VMCS_FIELD_S    (entry_ctr, iif,             VMCS_IDX_ENTRY_IIF,                        vmcs_int_t)
VMCS_FIELD      (entry_ctr, eec,             VMCS_IDX_ENTRY_EXCEPT_ERR_CODE,            u32_t)
VMCS_FIELD      (entry_ctr, instr_len,       VMCS_IDX_ENTRY_INSTR_LEN,                  u32_t)
VMCS_FIELD      (entry_ctr, msr_ld_cnt,      VMCS_IDX_ENTRY_MSR_LD_COUNT,               u32_t)
VMCS_FIELD_U64  (entry_ctr, msr_ld_addr,     VMCS_IDX_ENTRY_MSR_LD_ADDR_F)

/*******************************************************
 *
 * VM Exit Information
 *
 *******************************************************/
VMCS_FIELD_S    (exitinfo, reason,          VMCS_IDX_EINFO_EXIT_REASON,                vmcs_ei_reason_t)
VMCS_FIELD_S    (exitinfo, qual,            VMCS_IDX_EINFO_EXIT_QUAL,                  vmcs_ei_qual_t)
VMCS_FIELD_S    (exitinfo, int_info,        VMCS_IDX_EINFO_INTERRUPTION_INFO,          vmcs_int_t)
VMCS_FIELD      (exitinfo, int_ec,          VMCS_IDX_EINFO_INTERRUPTION_ERROR_CODE,    u32_t)
VMCS_FIELD_S    (exitinfo, idtvect_info,    VMCS_IDX_EINFO_IDT_VECTORING_INFO,         vmcs_int_t)
VMCS_FIELD      (exitinfo, idtvect_ec,      VMCS_IDX_EINFO_IDT_VECTORING_ERROR_CODE,   u32_t)
VMCS_FIELD      (exitinfo, instr_len,       VMCS_IDX_EINFO_INSTR_LEN,                  u32_t)
VMCS_FIELD_S    (exitinfo, vm_instr_info,   VMCS_IDX_EINFO_VM_INSTR_INFO,              vmcs_ei_vm_instr_t)
VMCS_FIELD      (exitinfo, vm_instr_err,    VMCS_IDX_EINFO_VM_INSTR_ERROR,             u32_t)
VMCS_FIELD      (exitinfo, linear_addr,     VMCS_IDX_EINFO_GUEST_LIN_ADDR,             word_t)


/*******************************************************
 *
 * VMCS
 *
 * The per-area init and do_vmentry_checks methods took `this' -- the VMCS
 * itself -- so they take a vmcs_t * here.  Bodies in arch/x86/x32/vmx.c.
 *
 *******************************************************/

void vmcs_gsarea_init (vmcs_t *self);
void vmcs_exectrarea_init (vmcs_t *self);
void vmcs_exitctrarea_init (vmcs_t *self);
void vmcs_entryctrarea_init (vmcs_t *self);
#if defined(CONFIG_DEBUG)
void vmcs_gsarea_do_vmentry_checks (vmcs_t *self, vmcs_entryctr_t i_entryctr, vmcs_int_t i_iif);
void vmcs_hsarea_do_vmentry_checks (vmcs_t *self, vmcs_entryctr_t i_entryctr, vmcs_exitctr_t i_exitctr);
void vmcs_exectrarea_do_vmentry_checks (vmcs_t *self);
void vmcs_exitctrarea_do_vmentry_checks (vmcs_t *self);
void vmcs_entryctrarea_do_vmentry_checks (vmcs_t *self);
void vmcs_do_vmentry_checks (vmcs_t *self);
#endif

/* Were the static members vmcs_t::alloc_vmcs / ::free_vmcs. */
vmcs_t *vmcs_alloc_vmcs (void);
void vmcs_free_vmcs (vmcs_t *vmcs);

/* Write initial state into the VMCS. */
void vmcs_init (vmcs_t *self);

extern vmcs_t *current_vmcs;

/* Load the VMCS pointer into the current physical processor. */
INLINE bool vmcs_is_loaded (const vmcs_t *self)
{
    return (current_vmcs == self);
}

INLINE bool vmcs_load (vmcs_t *self)
{
    if (EXPECT_TRUE (vmcs_is_loaded (self)))
	return true;

    current_vmcs = NULL;

    ASSERT (self != 0);
    ASSERT (((word_t) self & ~X86_PAGE_MASK) == 0);

    if (x86_vmsucceed (x86_vmptrld ((word_t) self)))
    {
	current_vmcs = self;
	return true;
    }

    return false;
}

INLINE bool vmcs_unload (vmcs_t *self)
{
    if (vmcs_is_loaded (self))
    {
	current_vmcs = NULL;
	return (x86_vmsucceed (x86_vmclear ((word_t) self)));
    }
    else
	return true;
}


INLINE word_t vmcs_read_register (vmcs_t *self, word_t idx)
{
    ASSERT (vmcs_is_loaded (self));
    return x86_vmread (idx);
}


INLINE bool vmcs_write_register (vmcs_t *self, word_t idx, word_t value)
{
    ASSERT (vmcs_is_loaded (self));
    return x86_vmwrite (idx, value);
}



#endif /* !__ARCH__X86__VMX_H__ */
